// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SweetTakeaway.Models;

namespace SweetTakeaway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SweetTakeaway.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Biscuits and cookies"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cakes"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Chocolate and candies"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Custards and puddings"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Deep-fried desserts"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Frozen desserts"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Jellied desserts"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Pastries"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Pies, cobblers, and clafoutis"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Sweet soups"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Dessert wines"
                        });
                });

            modelBuilder.Entity("SweetTakeaway.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\NiceBiscuits.jpg",
                            ImageUrl = "~\\images\\NiceBiscuits.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Some nice biscuits",
                            Price = 0.99m,
                            ShortDescription = "Some nice cookies for you."
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\ChocolateFudgeCake.jpg",
                            ImageUrl = "~\\images\\ChocolateFudgeCake.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Chocolate fudge cake",
                            Price = 99.99m,
                            ShortDescription = "The perfect cake to gift to your loved ones on birthdays."
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\GummyCandy.jpg",
                            ImageUrl = "~\\images\\GummyCandy.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Gunny candy",
                            Price = 0.09m,
                            ShortDescription = "Some gummy candy for you to chew while watching Netflix."
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\ChocolatePudding.jpg",
                            ImageUrl = "~\\images\\ChocolatePudding.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Chocolate pudding",
                            Price = 3.99m,
                            ShortDescription = "This chocolate pudding will make you smile."
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\DeepFriedBananas.jpg",
                            ImageUrl = "~\\images\\DeepFriedBananas.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Deep fried banana",
                            Price = 1.99m,
                            ShortDescription = "Bananas are even better when deep-fried. Try it now!"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\FreshStrawberryIceCream.jpg",
                            ImageUrl = "~\\images\\FreshStrawberryIceCream.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Fresh strawberry ice cream",
                            Price = 9.99m,
                            ShortDescription = "This ice cream will keep you fresh in sunny days!"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\SparklingRubyCabernetJellyWithCherries.jpg",
                            ImageUrl = "~\\images\\SparklingRubyCabernetJellyWithCherries.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Sparkling ruby cabernet jelly with cherries",
                            Price = 29.99m,
                            ShortDescription = "Now isn't that a fancy name? Buy one now and tell your friends about it!"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\AppleCinnamonPastries.jpg",
                            ImageUrl = "~\\images\\AppleCinnamonPastries.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Apple cinnamon pastries",
                            Price = 9.99m,
                            ShortDescription = "Get a bag and we'll double it!"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\BerryPie.jpg",
                            ImageUrl = "~\\images\\BerryPie.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Berry pie",
                            Price = 39.99m,
                            ShortDescription = "A delicious berry pie made just for you!"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\RoastedSweetPotatoAndCarrotSoup.jpg",
                            ImageUrl = "~\\images\\RoastedSweetPotatoAndCarrotSoup.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Roasted sweet potato and carrot soup",
                            Price = 9.99m,
                            ShortDescription = "Look! It's a potato and carrot soup made with love."
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ImageThumbnailUrl = "~\\images\\thumbnails\\AccordiniReciotoClassicoAcinatico2013.jpg",
                            ImageUrl = "~\\images\\AccordiniReciotoClassicoAcinatico2013.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Accordini recioto classico acinatico 1980",
                            Price = 499.99m,
                            ShortDescription = "This gorgeous wine from Veneto shows beautiful hues of ruby red in the glass."
                        });
                });

            modelBuilder.Entity("SweetTakeaway.Models.Product", b =>
                {
                    b.HasOne("SweetTakeaway.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
